name: Deploy to firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: create env file
      run: |
        touch .env
        echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
        echo REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} >> .env
        echo REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }} >> .env
        echo REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }} >> .env
        echo REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} >> .env
        echo REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }} >> .env
        echo REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }} >> .env
    - name: Setup the code
      run: npm install
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
